version: '3'

services:

  appleter:
    build:
      context: .
      dockerfile: ./.docker/appleter.production.dockerfile
    command: npm run build.prod
    container_name: appleter-build-prod
    image: appleter
    networks:
      - prod-network
    volumes:
      - ./dist:/home/app/appleter/dist

  appleter-nginx:
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/appleter.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: appleter-nginx-prod
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    image: nginx
    networks:
      - prod-network
    ports:
      - '5555:80'
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/appleter.template
      - ./dist/prod:/var/www/dist/prod

networks:
  prod-network:
    driver: bridge
