version: '3'

services:

  appleter:
    build:
      context: .
      dockerfile: ./.docker/appleter.development.dockerfile
    command: npm start
    container_name: appleter-start
    image: appleter
    networks:
      - dev-network
    ports:
      - '5555:5555'

networks:
  dev-network:
    driver: bridge
